### PR TITLE
Add new Pacemaker testing dependency

### PR DESCRIPTION
**Pull request by kgaillot**

### CODE REVIEW

**Comment by fabbione** [comment]
I like the approach but the install of optional packages is broken and multiarch for debian will break.

There is a major difference in:

for i in $optional_package; do
  $package_manager install $i || true
done

and:

$package_manager install $optional_packages || true

The former will attempt to install one package at a time and do the best it can to install them all, the former will fail if any of the optional_packages cannot be installed, failing for all of them.

For Debian, the install ordering is important. First x86_64 then alternative arch separately. This is necessary to deal  with the situation when foo-dev:$EXTRA_ARCH cannot be installed at the same time as foo-dev:x86_64.
The first update / install will pull in foo-dev:x86_64 (almost unavoidable) and the second run will install the target cross compiler arch. At least for now we need to keep it that way. The goal is to install $EXTRA_ARCH at build time to enable more cross compilation architectures (already requested by gfs2-utils a while back)

**Review by fabbione — CHANGES_REQUESTED** [review]
commet in the main review

**Comment by kgaillot** [comment]
updated commit per review

**Comment by fabbione** [comment]
ACK, looks good, I will merge it tomorrow after the CI maintenance.

**Pull request merged**
