### PR TITLE
Update Pacemaker configure and rpm options

### PR DESCRIPTION
**Pull request by kgaillot**
This tests more configure option variations, and ensures options are used only with branches that support them

### CODE REVIEW

**Review by chrissie-c — APPROVED** [review]
It seems reasonable to me from a CI perspective. All we an really do is do a run and check the config options do the right thing :)

**Comment by chrissie-c** [comment]
rpmbuild on opensuse failed because of 
[2024-06-05T08:25:17.510Z] make WITH="--with linuxha" rpm
[2024-06-05T08:25:17.510Z] make: *** No rule to make target 'linuxha"'.  Stop.

https://ci.kronosnet.org/job/pacemaker/job/pacemaker-pipeline/job/3.0/9/artifact/FAILED_buildrpms-opensuse-15-x86-64.log

I've taken that bit out of getProjectProperties.groovy for the time-being.

**Comment by kgaillot** [comment]
> rpmbuild on opensuse failed because of [2024-06-05T08:25:17.510Z] make WITH="--with linuxha" rpm [2024-06-05T08:25:17.510Z] make: *** No rule to make target 'linuxha"'. Stop.
> 
> https://ci.kronosnet.org/job/pacemaker/job/pacemaker-pipeline/job/3.0/9/artifact/FAILED_buildrpms-opensuse-15-x86-64.log
> 
> I've taken that bit out of getProjectProperties.groovy for the time-being.

Sorry, I had intended to merge the relevant change into the 3.0 branch beforehand, but CI wound up taking longer than my work day. It's merged now, you can put that back.

**Comment by chrissie-c** [comment]
Thanks. I've put that back and started another 3.0 build.

**Comment by chrissie-c** [comment]
There still seem to be some escape issues with this. Leave it with me though, it needs some CI-level investigation

**Comment by fabbione** [comment]
From a manual test, using WITH="--with linuxha" overrides the default from rpm/Makefile.am introducing more BR that are not installed on the nodes.

I am fine to add the BRs or we to expand WITH to include the rpm default.

**Comment by kgaillot** [comment]
> From a manual test, using WITH="--with linuxha" overrides the default from rpm/Makefile.am introducing more BR that are not installed on the nodes.
> 
> I am fine to add the BRs or we to expand WITH to include the rpm default.

Yep `WITH="--with linuxha --without doc"` should do it. Sometime in the next few months I expect to drop the doc option, so we'd have to update it again then, but that's not a big deal.

**Comment by kgaillot** [comment]
And if we need to get things up quickly, just drop WITH from ci-tools. I wanted to test that code path but it can wait.

**Comment by fabbione** [comment]
Yes I had to revert it to unblock CI rebuild today. We will find a way to get it going.

**Comment by chrissie-c** [comment]
I think it's working now but it was a slog. In the end I just had to add those options to props['WITH'] as there seems to be no way to get the options quoted and unquoted in a usable way. 

Well, there might be, but I've spent way too much time on it already!

**Pull request merged**
